### PR TITLE
chore: changes made to weekly update

### PR DESCRIPTION
**Pull request by treagan82**
Im running on near zero sleep this morning if I have screwed the pooch on this anywhere, please let me know and I will fix it sometime after im done sleeping through macroecon.

### CODE REVIEW

**Comment by cclinard84** [comment]
You can put these changes on your other PR. Just use `git checkout (branch-name)` make the changes, then use `git add (filename)`. Once that is complete do a `git commit` and then `git push`.

**Comment by treagan82** [comment]
changes made and pushed in, i dont have the option for a pull request though.

**Comment by xervir** [comment]
That’s because there’s already an open pull request for that branch.

**Comment by cclinard84** [comment]
Closing this PR. Make these changes on the original post PR.

**Pull request closed without merging**
